kind: pipeline
type: docker
name: default

workspace:
path: /drone/src

steps:
  - name: compile & run
    image: docker.gnivc.ru/maven:3.9.0-eclipse-temurin-17-alpine
    commands: # ваши команды сборки и запуска
      - mkdir out
      - javac -d out src/Main.java
      - java -cp out Main

  - name: bot test
    image: docker.gnivc.ru/javabot:2.0.0
    pull: always
    commands: # меняется только номер ДЗ
      - check start hw0103
